### ISSUE TITLE
Add a tab context menuitem

### ISSUE THREAD

**Issue by Gitoffthelawn** [Skeletonxf/duplicate-tab#1]
Can you add a tab context menuitem to perform the duplication so the toolbar button is not needed?

**Comment by Skeletonxf** [comment]
Do you mean this? https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Context_menu_items

**Comment by Gitoffthelawn** [comment]
Yes, but I recommend only showing the context menuitem when the user right-clicks on a tab.

**Comment by Skeletonxf** [comment]
I will look into adding this, thanks.

**Comment by Gitoffthelawn** [comment]
Great!  Thanks!

**Comment by Skeletonxf** [comment]
Added to version 1.3

**Comment by Gitoffthelawn** [comment]
Thank you!
