### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by JP-NYC** [Skeletonxf/duplicate-tab#12]
Great extension. I have been missing CloneWindow extension [https://www.bigdropinc.com/resources/mozilla/](url). Would love to have the option in your DuplicateTab to use the default key action (CTRL-N, CTRL-T) to duplicate current tab into new tab or open new window with current tab.

I know you are not supposed to be able to remap the default FF keys in FF 60+ but Cadeyrn [https://github.com/cadeyrn/newtaboverride](url) was able to do it by hooking into builtin new tab routine.

This would make the extension much more flexible and conducive to my browsing habits.

**Comment by Skeletonxf** [comment]
Sorry I don't understand why you say you have been missing CloneWindow. It looks like you can still install it from the URL to me?

I believe the extension in your second link changes the new tab page for all ways in which it is accessed (and hence CTRL+N and CTRL+T would have a different effect). Without looking into the details closely I think that overriding this new tab page and offering the ability to duplicate the previous tab open into the modified new tab page would require requesting permissions for all tabs/websites which I have already [discussed in a different issue](https://github.com/Skeletonxf/duplicate-tab/issues/8).

I'm not sure I quite understand what your use case is. Do you just want to remap CTRL+N and CTRL+T to perform tab duplication in the way already offered by ALT+SHIFT+D?

**Comment by JP-NYC** [comment]
CloneWindow is unsigned and the old type of XPI installer, so I can't get it to work or install even under about:debugging.

I see from your link that you don't want to request permissions for anything more than active tab.


And yes I would like toy get CTRL+N and CTRL+T to perform tab duplication in the way already offered by ALT+SHIFT+D, but vhanging to these keys in settings does not override the default behavior.


________________________________

**Comment by Skeletonxf** [comment]
In that case you should be able to cheat and use a system wide keyboard automation tool like [AutoHotKey](https://www.autohotkey.com/) or [AutoKey](https://github.com/autokey/autokey) which intercepts CTRL+T when you press it with Firefox open and sends ALT+SHIFT+D instead.

**Comment by Skeletonxf** [comment]
Closing this since it's been years and I don't think there's ever going to be a way for an extension to override default shortcuts in Firefox, so third party applications will be needed to intercept and remap.
