### ISSUE TITLE
[Feature] Move tab to new window

### ISSUE THREAD

**Issue by AdamPS** [Skeletonxf/duplicate-tab#14]
I would love a key that moves the current tab to a new window.  True you could say it's not part of "duplicate-tab" but it's quite similar and I think many users would find it helpful.

**Comment by Skeletonxf** [comment]
This will be easy to add to the advanced duplication menu as creating a new window is already performed by the code if there isn't an existing one. Unfortunately I'm quite busy the next few weeks so it might be some time before I can start implementing this feature.

**Comment by AdamPS** [comment]
Great, thanks for the reply.  I've just discovered that [Saka Key](https://addons.mozilla.org/en-US/firefox/addon/saka-key/) can already do this (set a key for "Move Tab New Window"), so in fact I'm happy if you want to just close this issue.  But sure, you might want to add it anyway, as other people might like it.

**Comment by Skeletonxf** [comment]
Released in version 3.0 on AMO

Wow that took far longer than it needed to!
