### ISSUE TITLE
Feature request: dark mode icon

### ISSUE THREAD

**Issue by cipricus** [Skeletonxf/duplicate-tab#18]
Now it looks odd in dark mode

![image](https://user-images.githubusercontent.com/3447868/167710554-5df0db13-244d-4603-aa0b-63cdc96a11ef.png)

**Comment by Skeletonxf** [comment]
I had no idea this was a thing! Looks easy enough to add in

**Comment by Skeletonxf** [comment]
A dark mode icon is now available in version 2.3 on AMO.
