### ISSUE TITLE
YouTube embedded videos not loading on duplicated tab

### ISSUE THREAD

**Issue by maxstarkenburg** [Skeletonxf/duplicate-tab#20]
Hi, first off, thanks for such a lovely and time-saving extension! Has saved me loads of time and keystrokes for my work testing needs.

I noticed an issue that, from what I can tell, seems to be resulting from loading a duplicated tab via this extension, since what I believe are native FF methods (e.g. right click on tab > "Duplicate Tab", or holding Option down while dragging a tab), don't seem to result in the problem.

When using this extension, YouTube video embeds don't seem to load. (Seem to happen regardless of using the "Duplicate tab" menu item in my FF toolbar overflow menu, or the keyboard shortcut I configured for this extension (Cmd+Shift+M).) For example, if I open https://developers.google.com/youtube/iframe_api_reference, then duplicate it via the extension, where the video originally was, there's now just an empty space. Even after hard-refreshing the page.

Just tried now with a Vimeo video, and it doesn't seem to be a problem with those, e.g. https://vimeo.zendesk.com/hc/en-us/articles/115007991707-Embeddable-playlists

I'm using Firefox 108.0.1 on MacOS Monterey 12.6 (apparently both of those wanting me to update them, heh, so I'll try to report back if things are different after doing so).

**Comment by Skeletonxf** [comment]
Hi thanks for the report

I can reproduce this on Firefox 108.0.1 on Linux too so at the least this doesn't seem operating system specific. However on Firefox Developer Edition 109.0b9 that embedded YouTube video seems to show as expected after duplicating, so I suspect this is an already fixed bug in Firefox?

If you're still getting this after updating please let me know - though Duplicate Tab just uses the Firefox tab API so it's unlikely I'll be able to do any fixes on my side.

**Comment by maxstarkenburg** [comment]
Hi again! Just got the FF 109 update on my machine, so took another gander (forgot to do so before this but after the MacOS Ventura update though, doh), and sure enough, this problem now seems to be resolved. (Also confirmed on my client sites where I was originally running into the problem, not just the above public example.) Will close. Thanks again!
