### ISSUE TITLE
[Feature] Customize icon

### ISSUE THREAD

**Issue by davidhs0** [Skeletonxf/duplicate-tab#21]
I have the last version of Firefox (110.0) and want use the new tab icon for duplicate the current tab, but there is not this option (only "Firefox Home (Default)" and "Black Page").

I remember this was possible some years ago with TabMixPlus extension: https://tabmixplus.org/support/viewtopic.php?t=3

I only found your extension for the new Firefox (with WebExtension).

Can you add the possibility of customize the icon used in toolbars? For example, I want use the icon "new tab" of my theme.

**Comment by Skeletonxf** [comment]
Hi, can you share a screenshot of what you mean? I'm not sure where "Firefox Home (Default)" and "Black Page" refers to.

**Comment by davidhs0** [comment]
This is the basic interface of Firefox. In red square I mark the standard button ("+" icon) for add a new tab.
![Button](https://user-images.githubusercontent.com/125702793/219872922-23f25c73-e8bd-4bb9-af96-6bd877c9e3ad.png)

In this image, I moved the "new tab" button to toolbar (red square) and in settings I can modify the function of this button (green square), but I can not open a duplicate of current tab.
![Button moved](https://user-images.githubusercontent.com/125702793/219872983-64bce806-5b72-4f41-9958-b4733675247e.png)

In my Firefox I installed some extensions and I used https://github.com/Aris-t2/CustomCSSforFx and https://github.com/B00ze64/FF-Menu-Icon-Plus-CSS in order to customize the theme. Now I have two "new tab" buttons (red square), the standard (with the icon of my theme) and the your (with your icon).
![Button double](https://user-images.githubusercontent.com/125702793/219873000-ec8d592c-cdcc-44f9-80f8-2b5e02ff13c1.png)

I want change the icon of your button by the "new tab" icon of my theme. Perhaps this is possible with files userChrome.css and userContent.css (how?) or you need modify your code.

**Comment by Skeletonxf** [comment]
Hi, thanks for giving more detail. I think this is best suited to `userChrome.css` - I've had a quick look and I'm fairly confident it is possible to override browser extension icons (e.g https://www.reddit.com/r/FirefoxCSS/comments/ny6w3n/replacing_extension_icon/).

**Comment by davidhs0** [comment]
Thanks for the link.

Done! I write here my solution.

The CSS style of your button is
```
#_54fa1e34-a0ad-4526-a81b-b06139adf332_-BAP {
  --webextension-menupanel-image: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
  --webextension-menupanel-image-light: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork-dark.svg");
  --webextension-menupanel-image-dark: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
  --webextension-menupanel-image-2x: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
  --webextension-menupanel-image-2x-light: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork-dark.svg");
  --webextension-menupanel-image-2x-dark: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
  --webextension-toolbar-image: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
  --webextension-toolbar-image-light: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork-dark.svg");
  --webextension-toolbar-image-dark: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
  --webextension-toolbar-image-2x: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
  --webextension-toolbar-image-2x-light: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork-dark.svg");
  --webextension-toolbar-image-2x-dark: url("moz-extension://96703920-ffc9-4688-ae58-704fcae7c631/icons/fork.svg");
}
```

Notes:
- I do not know if the id _54fa1e34-a0ad-4526-a81b-b06139adf332_-BAP is always this or only in my case.
- --webextension-menupanel-image* set the icons show in list of extensions. These must be not modify.
- --webextension-toolbar-image* set the icons show in toolbar.

I add the code in userChrome.css (path: C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/) and my_icon.png in the folder chrome. I do not know why, but if I write relative path this do not work: url("my_icon.png"), or url("./my_icon.png"), so I must write the absolute path: url("file:///C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/my_icon.png").

The code is
```
#_54fa1e34-a0ad-4526-a81b-b06139adf332_-BAP {
  --webextension-toolbar-image: url("file:///C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/my_icon.png") !important;
  --webextension-toolbar-image-light: url("file:///C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/my_icon.png") !important;
  --webextension-toolbar-image-dark: url("file:///C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/my_icon.png") !important;
  --webextension-toolbar-image-2x: url("file:///C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/my_icon.png") !important;
  --webextension-toolbar-image-2x-light: url("file:///C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/my_icon.png") !important;
  --webextension-toolbar-image-2x-dark: url("file:///C:/Users/my-user/AppData/Roaming/Mozilla/Firefox/Profiles/my-profile/chrome/my_icon.png") !important;
}
```
