### ISSUE TITLE
Keyboard shortcuts do not work in Firefox ESR (52.7.4)

### ISSUE THREAD

**Issue by dswhite42** [Skeletonxf/duplicate-tab#5]
Hello.  I'm running the ESR release of Firefox (52.7.4) on Windows 10 and the keyboard shortcut simply does not seem to work.  I first had to disable ALT-SHIFT-D in the "Web Developer" extension - that shortcut was bound to "Edit CSS".  But even after doing that and restarting Firefox, ALT-SHIFT-D does not do anything at all.  (and CTRL-SHIFT-D just brings up the "New Bookmarks" window.  I have both the "Duplicate Tab 1" and "Duplicate Tab 2" boxes checked in the extension's options page.)

Thanks.

**Comment by Skeletonxf** [comment]
It's a known issue that various shortcuts conflict and don't work. :/ If you can wait a little bit longer the next ESR release should support configurable shortcuts (v60) and then you will be able to redefine them to something that does work.

You can also try editing manifest.json to select different shortcuts and then installing the fork locally - though I doubt the ESR will let you keep a local installation between restarts.

**Comment by Skeletonxf** [comment]
As the v60 ESR release is now out I believe this issue is solved.
